project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "lessons/*.qmd"
    - "!material/"

execute:
  freeze: auto

website:
  title: "Programování pro GIS a DPZ"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Ćást 1: Model Builder"
        menu:
          - text: "Lekce 1: Jednoduchý model"
            href: lessons/lesson_01.qmd
      - text: "Část 2: Úvod do Pythonu"
        menu:
          - text: "Lekce 3: První program v Pythonu"
            href: lessons/lesson_03.qmd
          - text: "Lekce 4: Cykly a podmínky"
            href: lessons/lesson_04.qmd
          - text: "Lekce 5: Tvorba jednoduchého algoritmu"
            href: lessons/lesson_05.qmd
          - text: "Lekce 6: Funkce a moduly"
            href: lessons/lesson_06.qmd
          - text: "Lekce 7: Textové soubory I"
            href: lessons/lesson_07.qmd
          - text: "Lekce 8: Textové soubory II"
            href: lessons/lesson_08.qmd

format:
  html:
    theme: cosmo
    toc: true