project:
  type: website
  output-dir: docs

website:
  title: "Programování pro GIS a DPZ"
  navbar:
    left:
      - text: "Home"
        href: index.md
      - text: "Model Builder"
        menu:
          - text: "Lekce 1: Jednoduchý model"
            href: lessons/lesson_01.qmd
      - text: "Úvod do Pythonu"
        menu:
          - text: "Lekce 3: První program v Pythonu"
            href: lessons/lesson_03.qmd

format:
  html:
    theme: cosmo
    toc: true